name: Docker Image CI

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: arc-runner-{{ github.event.repository.name }}

    steps:
      - name: Check out main repository
        uses: actions/checkout@v4
      - name: Login to Cluster Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cluster.megaver.se
          username: robot$github
          password: ${{ secrets.HARBOR_TOKEN_ROBOT_GITHUB }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Produce all tags
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: registry.cluster.megaver.se/library/{{ github.event.repository.name }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=run-${{ github.run_number }}-${{ github.run_attempt }}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
